---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wiraland/website/staging/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -rf $DEPLOYPATH/.cpanel.yml
    - /bin/rm -rf $DEPLOYPATH/.gitignore
    # - ln -s $DEPLOYPATH/public/* /home/temw7575/public_html
    # - ln -s $DEPLOYPATH/storage/app/public/ /home/temw7575/public_html/storage
